FROM denoland/deno:latest
ARG VERSION
# ENV DENO_DEPLOYMENT_ID=${VERSION}
ENV PORT=5411

WORKDIR /app

COPY . .
RUN deno cache main.ts

EXPOSE 5411

CMD ["run", "--config", "./deno.jsonc", "-A", "main.ts"]